name: Build and Deploy Projects
on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/build.yml'
      - 'alphabet_adventure/**'
  workflow_dispatch:
    inputs:
      project:
        description: 'Project to deploy'
        required: true
        type: choice
        options:
          - alphabet_adventure
          - all
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'
        type: choice
        options:
          - production
          - staging

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-alphabet-adventure:
    if: github.event_name == 'workflow_dispatch' || github.event_name == 'push'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./alphabet_adventure
    steps:
      - uses: actions/checkout@v4
      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./alphabet_adventure/dist
          destination_dir: alphabet_adventure
          force_orphan: true
